# Generated by Django 5.1.2 on 2024-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_bmi_alter_profile_blood_pressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_sugar_target',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=170),
            preserve_default=False,
        ),
    ]
