# Generated by Django 5.1.2 on 2024-10-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
