# Generated by Django 5.1.2 on 2024-10-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sodium', models.FloatField()),
                ('carbs', models.FloatField()),
                ('calories', models.FloatField()),
                ('ingredients', models.ManyToManyField(to='app.ingredient')),
            ],
        ),
    ]
